# https://taskfile.dev
version: '3'

tasks:
  default:
    cmds:
      - task: build

  build:
    cmds:
      - go build -tags assert -o bin/slowfs main.go
    sources:
      - ./**/*.go
    generates:
      - ./bin/slowfs

  build-linux:
    cmds:
      - GOARCH=amd64 GOOS=linux go build -tags assert -o bin/linux-amd64/slowfs main.go

  build-darwin:
    cmds:
      - GOARCH=arm64 GOOS=darwin go build -tags assert -o bin/darwin-arm64/slowfs main.go

  clean:
    cmds:
      - rm -rf bin/

  install-tools:
    cmds:
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

  lint:
    cmds:
      - golangci-lint run

  test:
    cmds:
      - go test ./...

  pb:
    cmds:
      - >
        protoc
        -I=slowfs
        --go-grpc_out=paths=source_relative:pb
        --go_out=paths=source_relative:pb
        slowfs.proto

  install:
    cmds:
      - task: build
      - install -D ./bin/slowfs /usr/local/bin/slowfs
