# https://taskfile.dev
version: '3'

vars:
  GO_BUILD_FLAGS: -tags assert -trimpath

tasks:
  default:
    cmds:
      - task: build

  build:
    cmds:
      - go build {{.GO_BUILD_FLAGS}} -o bin/slowio main.go
    sources:
      - ./**/*.go
    generates:
      - ./bin/slowio

  build-linux:
    cmds:
      - GOARCH=amd64 GOOS=linux go build {{.GO_BUILD_FLAGS}} -o bin/linux-amd64/slowio main.go

  build-darwin:
    cmds:
      - GOARCH=arm64 GOOS=darwin go build {{.GO_BUILD_FLAGS}} -o bin/darwin-arm64/slowio main.go

  clean:
    cmds:
      - rm -rf bin/

  install-tools:
    cmds:
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

  lint:
    cmds:
      - golangci-lint run

  test:
    cmds:
      - go test ./...

  pb:
    cmds:
      - >
        protoc
        -I=slowio
        --go-grpc_out=paths=source_relative:pb
        --go_out=paths=source_relative:pb
        slowio.proto

  install:
    cmds:
      - task: build
      - install -D ./bin/slowio /usr/local/bin/slowio
